#!/usr/bin/env python3
"""Export food poisoning chart data from SQLite to a FE module."""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
from pathlib import Path


PATHOGEN_NAMES = [
    "諾羅病毒",
    "金黃色葡萄球菌",
    "仙人掌桿菌",
    "沙門氏桿菌",
    "腸炎弧菌",
    "病原性大腸桿菌",
    "肉毒桿菌",
    "輪狀病毒",
    "病因不明",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", default="data/food_poisoning.sqlite", help="SQLite DB path")
    parser.add_argument(
        "--output",
        default="Taipei-City-Dashboard-FE/src/store/foodPoisoningPatientsData.js",
        help="Generated frontend JS module",
    )
    return parser.parse_args()


def normalize_pathogen(raw_item: str, item: str) -> str | None:
    if "病因物質不明合計" in raw_item:
        return "病因不明"

    normalized = item
    normalized = re.sub(r"^(細菌|天然毒|化學物質)-", "", normalized)
    normalized = normalized.replace("植物性(含蕈類)", "植物性")
    normalized = re.sub(r"\s+", "", normalized)

    aliases = {
        "諾羅病毒": "諾羅病毒",
        "金黃色葡萄球菌": "金黃色葡萄球菌",
        "仙人掌桿菌": "仙人掌桿菌",
        "沙門氏桿菌": "沙門氏桿菌",
        "腸炎弧菌": "腸炎弧菌",
        "病原性大腸桿菌": "病原性大腸桿菌",
        "肉毒桿菌": "肉毒桿菌",
        "輪狀病毒": "輪狀病毒",
    }
    return aliases.get(normalized)


def fetch_series(conn: sqlite3.Connection) -> list[dict]:
    years = [
        row[0]
        for row in conn.execute("SELECT roc_year FROM yearly_totals ORDER BY roc_year")
    ]
    series = []
    for year in years:
        total_cases, total_patients = conn.execute(
            "SELECT cases, patients FROM yearly_totals WHERE roc_year = ?",
            (year,),
        ).fetchone()
        monthly_cases = [
            row[0]
            for row in conn.execute(
                "SELECT cases FROM monthly_stats WHERE roc_year = ? ORDER BY month",
                (year,),
            )
        ]
        monthly_patients = [
            row[0]
            for row in conn.execute(
                "SELECT patients FROM monthly_stats WHERE roc_year = ? ORDER BY month",
                (year,),
            )
        ]

        pathogen_patients = {name: 0 for name in PATHOGEN_NAMES}
        for raw_item, item, patients in conn.execute(
            """
            SELECT raw_item, item, patients
            FROM table_rows
            WHERE roc_year = ?
              AND table_type = 'pathogen'
              AND is_summary = 0
            ORDER BY row_order
            """,
            (year,),
        ):
            normalized = normalize_pathogen(raw_item, item)
            if normalized in pathogen_patients:
                pathogen_patients[normalized] += patients

        unknown = conn.execute(
            """
            SELECT patients
            FROM table_rows
            WHERE roc_year = ?
              AND table_type = 'pathogen'
              AND raw_item LIKE '%病因物質不明合計%'
            """,
            (year,),
        ).fetchone()
        if unknown:
            pathogen_patients["病因不明"] = unknown[0]

        series.append(
            {
                "name": f"{year}年",
                "cases": total_cases,
                "patients": total_patients,
                "monthly": monthly_patients,
                "monthly_cases": monthly_cases,
                "monthly_patients": monthly_patients,
                "pathogens": [
                    {"x": name, "y": pathogen_patients[name]}
                    for name in PATHOGEN_NAMES
                ],
            }
        )
    return series


def write_module(output_path: Path, series: list[dict]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    module = (
        "// Generated by scripts/export_food_poisoning_chart_data.py from data/food_poisoning.sqlite.\n"
        "// Monthly values include both case counts and patient counts; pathogen values are patient counts.\n\n"
        f"export const FOOD_POISONING_PATIENT_PATHOGENS = {json.dumps(PATHOGEN_NAMES, ensure_ascii=False, indent=2)};\n\n"
        f"export const foodPoisoningPatientSeries = {json.dumps(series, ensure_ascii=False, indent=2)};\n"
    )
    output_path.write_text(module, encoding="utf-8")


def main() -> None:
    args = parse_args()
    conn = sqlite3.connect(args.db)
    try:
        write_module(Path(args.output), fetch_series(conn))
    finally:
        conn.close()


if __name__ == "__main__":
    main()
